name: CI Locadora API
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
jobs:
  build-and-test:
    name: Build e Testes
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: locadora
          POSTGRES_PASSWORD: locadora123
          POSTGRES_DB: locadora_db
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build com Maven
        run: mvn -B clean compile

      - name: Rodar Testes
        run: mvn -B test
